### PR TITLE
READY: gpb boolean compatibility with erlang_protobuffs

### PR DESCRIPTION
**Pull request by lukebakken**
Related to tomas-abrahamsson/gpb#63

See PR tomas-abrahamsson/gpb#64

### CODE REVIEW

**Comment by tomas-abrahamsson** [comment]
About the `function_clause`, you would need to adapt [`gpb_compile:format_bool_encoder`](https://github.com/basho/gpb/blob/6a3ff6a91e30288b96bc5d34a07b60f36158cafe/src/gpb_compile.erl#L2490) too. In case you've not already discovered it, it might be useful to know, that the eunit tests are a bit odd in that _`gpb_compile_tests.erl`_ includes _`gpb_tests.erl`_ since most of the encoding/decoding tests has to work the same way for both `gpb` and the code generated by `gpb_compile`, but I didn't want to duplicate all encoding/decoding unit tests.

A method I often use for debugging these kinds of eunit issues is to `gpb_compile:file(xyz, [{{msg,m1},...]).` from within an erlang shell, then take a look at the generated _`xyz.erl`_ to figure out what went wrong. (First running `rr(".../gpb/include/*.hrl"),rr(".../gpb/test/*.erl").` makes copy/paste a little easier.)

Looks generally good, it would also be good if the type specs could indicate that `0` and `1` are allowed, see [`gpb_compile:type_to_typestr_2`](https://github.com/basho/gpb/blob/6a3ff6a91e30288b96bc5d34a07b60f36158cafe/src/gpb_compile.erl#L5324)

Another thing to tend to might be nifs: see [`gpb_compile:format_nif_cc_field_packer_single`](https://github.com/basho/gpb/blob/6a3ff6a91e30288b96bc5d34a07b60f36158cafe/src/gpb_compile.erl#L6228). For unit testing you might want to have a look at [`gpb_compile_tests:nif_with_strbin`](https://github.com/basho/gpb/blob/6a3ff6a91e30288b96bc5d34a07b60f36158cafe/test/gpb_compile_tests.erl#L1542) for some previous example of similar nature.

**Comment by tomas-abrahamsson** [comment]
I was thinking about one more thing: It was good that you remembered about parsing default values for booleans, I did not think of that myself, but it makes sense of course. I was wondering, do you think, would it be useful if there was some kind of normalization, of such default values for booleans, so that after parsing there was only `true | false` and `1 | 0` be normalized to `true | false`? I'm not sure myself, so raising the issue, but I think I'm leaning a bit towards normalization.

**Comment by lukebakken** [comment]
@tomas-abrahamsson - thank you for all the information about debugging, that will help me out a lot.

As for default values, I think the protobuf spec only allows `true` and `false`, actually:

https://developers.google.com/protocol-buffers/docs/proto#optional

In the `riak_pb` code, only `true` and `false` is used. I don't think `0` and `1` will be necessary in default values.

**Comment by tomas-abrahamsson** [comment]
> As for default values, I think the protobuf spec only allows true and false

Good catch, you seem to be right:

``` protobuf
    message m1 {
      required bool f1 = 1 [default=0];
      required bool f2 = 2 [default=1];
      required bool f3 = 3 [default=false];
      required bool f4 = 4 [default=true];
    }
```

Then:

``` sh
    % protoc --cpp_out `pwd` bool.proto
    bool.proto:2:37: Expected "true" or "false".
    bool.proto:3:37: Expected "true" or "false".
```

**Comment by lukebakken** [comment]
Very clever way to validate that, I will put it in my "bag of protobuf tricks"

**Comment by lukebakken** [comment]
Going to close this PR and will get the changes from PR tomas-abrahamsson/gpb#64

**Pull request closed without merging**
